apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ExternalName
  externalName: usermgmtdb.cguzkpeluoeq.us-east-2.rds.amazonaws.com

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-flask
  template:
    metadata:
      labels:
        app: frontend-flask
    spec:
      containers:
        - name: frontend-flask
          image: varunjoshi0404/flask-usermgmt-api:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql-svc
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: usermgmt
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              value: mypassword

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-flask-svc
spec:
  selector:
    app: frontend-flask
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000